#                                 ___ _   
#                                /   | |  
#  ___ _ __ __ _ _____   _  ___ / /| | |_ 
# / __| '__/ _` |_  / | | |/ __/ /_| | __|
#| (__| | | (_| |/ /| |_| | (__\___  | |_ 
# \___|_|  \__,_/___|\__, |\___|   |_/\__|
#                     __/ |               
#                    |___/                
#----------- Made by crazyc4t --------------
#         https://saidneder.tech

# Prompt format showing username and hostname
format = """
[\\[$username@$hostname\\] ](bold green)$directory$all$character"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Shell symbol
[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

# Username preferences
[username]
show_always = true
style_user = "blue bold"
disabled = false
format ="[$user]($style)"

# Hostname preferences
[hostname]
ssh_only = false
format = "[$hostname]($style)"
style = "blue bold"
disabled = false

